name: Docs

on:
  push:
    branches:
      - main
    paths:
      - "apps/docusaurus/**"
      - "apps/examples/**"
      - "packages/**"
      - "nx.json"
      - "tsconfig.base.json"
      - "package.json"
      - "yarn.lock"
  workflow_dispatch: {}

jobs:
  call-ci:
    uses: ./.github/workflows/ci.yml
    with:
      run-docs: true
      docs-publish: true
    secrets: inherit
